version: 2.0

references:

  workspace_root: &workspace_root
      /opt/workspace/

  container_config: &container_config
    docker:
      - image: menny/android_ndk:1.7.1

    working_directory: *workspace_root

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      _GRADLE_OPTIONS: '-Dorg.gradle.parallel=false -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx1560m -XX:+HeapDumpOnOutOfMemoryError"'
      ROOM_ID: 80853324
      TEAM: "[To:2135825][To:2198020][To:2198033][To:1979687][To:2423114][To:2391265]"
      REVIEWDOG_VERSION: 0.9.3


  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
      key: androidci-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  build:
    <<: *container_config
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Setup environment
          command: scripts/ci_setup.sh

      - run:
          name: Initial build
          command: scripts/ci_assemble.sh

      - store_artifacts:
          path: /opt/workspace/app/build/outputs/apk/
          destination: apks/

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

      - save_cache:
          <<: *general_cache_key
          paths:
            - "~/.gradle"
            - "~/.m2"
            - "/opt/android-sdk-linux/licenses/"
          cache_directories:
          # Android SDK
          - /usr/local/android-sdk-linux/tools
          - /usr/local/android-sdk-linux/platform-tools
          - /usr/local/android-sdk-linux/build-tools
          - /usr/local/android-sdk-linux/licenses
          - /usr/local/android-sdk-linux/extras/google/m2repository

          # Gradle caches
          - /home/ubuntu/.gradle/caches/
          - /home/ubuntu/.gradle/wrapper/

  check:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Checks
          command: ./scripts/ci_check.sh

      - store_artifacts:
          path: /opt/workspace/app/build/reports/
          destination: lint_reports/app/

      - store_artifacts:
          path: /opt/workspace/base/build/reports/
          destination: lint_reports/base/

      - store_artifacts:
          path: /opt/workspace/jnidictionaryv1/build/reports/
          destination: lint_reports/jnidictionaryv1/

      - store_artifacts:
          path: /opt/workspace/jnidictionaryv2/build/reports/
          destination: lint_reports/jnidictionaryv2/

      - store_artifacts:
          path: /opt/workspace/nextword/build/reports/
          destination: lint_reports/nextword/

  test:
    <<: *container_config
    parallelism: 3
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Run Tests
          command: |
            export TEST_GROUP_INDEX=${CIRCLE_NODE_INDEX}
            export TEST_GROUPS_COUNT=${CIRCLE_NODE_TOTAL}
            echo "Running test group ${TEST_GROUP_INDEX} out of ${TEST_GROUPS_COUNT}..."
            ./scripts/ci_test.sh

      - store_artifacts:
          path: app/build/reports/tests/
          destination: tests_reports/

      - store_test_results:
          path: /opt/workspace/app/build/test-results

  post_comment:
    docker:
      - image: circleci/ruby:2.3
      working_directory: /opt/workspace/
    steps:
      - run:
          name: Comment to github
          command: scripts/saddler.sh

workflows:
  version: 2

  build_check_tests_deploy:
    jobs:
      - build
      - check:
          requires:
            - build
      - test:
          requires:
            - build
      - post_comment:
          requires:
            - build
